/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthCallback: typeof import('./src/components/AuthCallback.vue')['default']
    ChallengeForm: typeof import('./src/components/ChallengeForm.vue')['default']
    DebugAuth: typeof import('./src/components/DebugAuth.vue')['default']
    EventCard: typeof import('./src/components/EventCard.vue')['default']
    EventForm: typeof import('./src/components/EventForm.vue')['default']
    ForgotPasswordForm: typeof import('./src/components/ForgotPasswordForm.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    LeaderboardTable: typeof import('./src/components/LeaderboardTable.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PhotoUpload: typeof import('./src/components/PhotoUpload.vue')['default']
    RedemptionModal: typeof import('./src/components/RedemptionModal.vue')['default']
    RichTextDisplay: typeof import('./src/components/RichTextDisplay.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./src/components/SignupForm.vue')['default']
    StatsCards: typeof import('./src/components/StatsCards.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_db0@0.3.2_embla-carousel@8.6.0_ioredis@5.6.1_jwt-de_24ea6e6297aafa923d9274880d3c9a3e/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.0_@babel+parser@7.27.5_db0@0.3.2_embla-carousel@8.5.2_ioredis@5.6.1_jwt-de_de66ac971528df341627f723e7c39d84/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UProgress: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@3.1.3_@babel+parser@7.27.5_axios@1.10.0_db0@0.3.2_embla-carousel@8.6.0_ioredis_d713be22aff4b7dc44c37386e43058bd/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
