AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SAM template for User Group Management Site Backend

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        EVENTS_TABLE: !Ref EventsTable
        SUBMISSIONS_TABLE: !Ref SubmissionsTable
        REDEMPTIONS_TABLE: !Ref RedemptionsTable
        CREDITS_VOUCHERS_TABLE: !Ref CreditsVouchersTable
        REDEMPTION_EMAIL_QUEUE_URL: !Ref RedemptionEmailQueue
        SENDER_EMAIL: "dipigom256@ofacer.com"  # Replace with your verified SES email
    AutoPublishAlias: live
    CodeUri: ./src/

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      
  CreditsVouchersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: credits_vouchers
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: TypeIndex
          KeySchema:
            - AttributeName: type
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: events
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  SubmissionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: submissions
      AttributeDefinitions:
        - AttributeName: submissionId
          AttributeType: S
        - AttributeName: submittedAt
          AttributeType: S
        - AttributeName: submittedBy
          AttributeType: S
      KeySchema:
        - AttributeName: submissionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: SubmittedByIndex
          KeySchema:
            - AttributeName: submittedBy
              KeyType: HASH
            - AttributeName: submittedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # New Redemptions Table
  RedemptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: redemptions
      AttributeDefinitions:
        - AttributeName: redemptionId
          AttributeType: S
        - AttributeName: userEmail
          AttributeType: S
        - AttributeName: redemptionDate
          AttributeType: S
      KeySchema:
        - AttributeName: redemptionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserEmailIndex
          KeySchema:
            - AttributeName: userEmail
              KeyType: HASH
            - AttributeName: redemptionDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  # SQS Queue for Redemption Emails
  RedemptionEmailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: redemption-email-queue
      VisibilityTimeout: 60
      MessageRetentionPeriod: 1209600  # 14 days

  # S3 Bucket for Image Storage
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "user-group-management-images-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            ExposedHeaders: []


  # S3 Bucket Policy for Public Read Access
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ImagesBucket.Arn}/*"

  # Lambda Functions - User Management
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/createUser.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: POST

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getUser.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users/{email}
            Method: GET

  GetUserByEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getUserByEmail.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetUserByEmail:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users/email/{email}
            Method: GET

  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getAllUsers.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users
            Method: GET

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/updateUser.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /users/email/{email}
            Method: PUT

  # Lambda Functions - Event Management
  GetEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getEvents.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvents:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /events
            Method: GET

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/createEvent.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /events
            Method: POST

  UpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/updateEvent.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /events/{eventId}
            Method: PUT

  DeleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/deleteEvent.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /events/{eventId}
            Method: DELETE

  # Lambda Functions - Submission Management
  CreateSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/createSubmission.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreateSubmission:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions
            Method: POST

  GetSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getSubmission.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetSubmission:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions/{submissionId}
            Method: GET

  GetSubmissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getSubmissions.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetSubmissions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions
            Method: GET
        GetUserSubmissions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions/user/{email}
            Method: GET

  UpdateSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/updateSubmission.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UpdateSubmission:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions/{submissionId}
            Method: PUT

  GetSubmissionStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getSubmissionStats.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetSubmissionStats:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions/stats
            Method: GET

  DeleteSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/deleteSubmission.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        DeleteSubmission:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /submissions/{submissionId}
            Method: DELETE
            
  # Lambda Functions - Credits and Vouchers Management
  UploadCreditsVouchersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/uploadCreditsVouchers.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UploadCreditsVouchers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /credits-vouchers/upload
            Method: POST
            
  GetCreditsVouchersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getCreditsVouchers.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetCreditsVouchers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /credits-vouchers
            Method: GET
            
  RedeemCreditVoucherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/redeemCreditVoucher.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        RedeemCreditVoucher:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /credits-vouchers/redeem
            Method: POST

  GetAllRedemptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getAllRedemptions.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetAllRedemptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /redemptions
            Method: GET

  GetUserRedemptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/getUserRedemptions.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetUserRedemptions:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /credits-vouchers/user
            Method: POST

  # Lambda Function for sending redemption emails
  SendRedemptionEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/sendRedemptionEmail.handler
      CodeUri: src/
      Role: !GetAtt EmailLambdaExecutionRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RedemptionEmailQueue.Arn
            BatchSize: 1

  # Lambda Function - Image Upload
  UploadImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/uploadImage.handler
      CodeUri: src/
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          IMAGES_BUCKET_NAME: !Ref ImagesBucket
      Events:
        UploadImage:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /upload
            Method: POST

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: UserGroupManagementUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: linkedinurl
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: githuburl
          AttributeDataType: String
          Mutable: true
          Required: false

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: user-group-management-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  # IAM Roles and Policies
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt EventsTable.Arn
                  - !GetAtt SubmissionsTable.Arn
                  - !GetAtt RedemptionsTable.Arn
                  - !GetAtt CreditsVouchersTable.Arn
                  - !Sub "${SubmissionsTable.Arn}/index/*"
                  - !Sub "${RedemptionsTable.Arn}/index/*"
                  - !Sub "${CreditsVouchersTable.Arn}/index/*"
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub "${ImagesBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !GetAtt ImagesBucket.Arn
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueUrl
                Resource: !GetAtt RedemptionEmailQueue.Arn

  # Special role for email sending Lambda with SES permissions
  EmailLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      Policies:
        - PolicyName: SESAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource: "*"

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    
  ImagesBucketName:
    Description: S3 Bucket for storing images
    Value: !Ref ImagesBucket
    
  ImagesBucketUrl:
    Description: S3 Bucket URL for images
    Value: !Sub "https://${ImagesBucket}.s3.${AWS::Region}.amazonaws.com"
    
  RedemptionEmailQueueUrl:
    Description: SQS Queue URL for redemption emails
    Value: !Ref RedemptionEmailQueue